
path: "/Users/dawid/Documents/Coding/Visual Studio/Robotic_Arm/source/Infrastracture Layer/training_images"  # dataset root dir
train: "images/train"  # train images (relative to 'path')
val: "images/val"  # val images (relative to 'path')

# Classes
names:
  0: Rubber_duck